//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enemy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Skin { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> Speed { get; set; }

        public static Enemy from(Enemy template)
        {
            Enemy e = new Enemy();
            e.Id = template.Id;
            e.Name = template.Name;
            e.Skin = template.Skin;
            e.HP = template.HP;
            e.Damage = template.Damage;
            e.Points = template.Points;
            return e;
        }
    }
}
